# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include: ['master']
  
variables:
  buildConfiguration: 'Release'
  workingDirectory: '$(Build.SourcesDirectory)'

steps:
- script: dotnet restore ./magnett-automation-core.sln
  displayName: Restore
  workingDirectory: $(workingDirectory)

- script: dotnet build ./magnett-automation-core.sln --configuration $(buildConfiguration)
  displayName: Build
  workingDirectory: $(workingDirectory)

- script: dotnet test ./magnett-automation-core.sln --configuration $(buildConfiguration) --logger trx
  displayName: Test
  workingDirectory: $(workingDirectory)

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish ./Magnett.Automation.Core --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish
  workingDirectory: $(workingDirectory)
  
- task: PublishBuildArtifacts@1
