# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include: ['master']
  
variables:
  buildConfiguration: 'Release'
  workingDirectory: '$(Build.SourcesDirectory)'
  solutionFile: './magnett-automation-core.sln'
  pojectFile: '$(Build.SourcesDirectory)/src/magnett.automation.core/magnett.automation.core.csproj'

steps:
- script: dotnet restore $(solutionFile)
  displayName: Restore
  workingDirectory: $(workingDirectory)

- script: dotnet build $(solutionFile) --configuration $(buildConfiguration)
  displayName: Build
  workingDirectory: $(workingDirectory)

- script: dotnet test $(solutionFile) --configuration $(buildConfiguration) --logger trx
  displayName: Test
  workingDirectory: $(workingDirectory)

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish $(pojectFile) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish
  workingDirectory: $(workingDirectory)
  
- task: PublishBuildArtifacts@1
