name: Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  
    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
    - name: Publish the package to nuget.org
      run: dotnet nuget push */*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
